# Generated by Django 4.2.6 on 2023-10-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_image_produto_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marqueting',
            new_name='preco_marketing',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marqueting_promocional',
            new_name='preco_marketing_promocional',
        ),
    ]
