# Generated by Django 4.2.6 on 2023-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_preco_marqueting_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='Produto',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
